### ISSUE TITLE
Q: How to add more Sprite/Image Paths

### ISSUE THREAD

**Issue by michaelcurry** [ScripterSugar/wdfp-extractor#15]
After diving into the code a bit, I am at a point where I believe I need to ask for help.  I am attempting to retrieve images/sprites such as `scene/general/sprite_sheet/vector_icon_color-assets/recommended_element_blue` or `scene/general/sprite_sheet/letterbox-assets/game_title_logo`...  Pretty much everything in `scene/general/sprite_sheet`

Unfortunately when i run the command, I get this:
```
Target region set as gl
Executing command sprite scene/general/sprite_sheet/vector_icon_color-assets/recommended_element_blue
Initializing extraction process.
Loading saved hashmap.
Image not found.
Process done in 0.19s
```

Side Note: I got the code base up and running on my machine for development, and would be happy to add these, and other paths to the project if a path forward is found.

Thank you for helping out 😃

**Comment by michaelcurry** [comment]
What i have currently tried: 

1. I have also run the `checkUnknowns` command and manually checked all exported images, but no element images/sprites were found 🤔 

2. I updated `/assets/boot_ffc6.as` as US version 0.51 (apk) before `Extract Data`, but no new images seemed to be exported.

**Comment by ScripterSugar** [comment]
Some assets, especially those with prefix `scene/general`, are not downloadable through asset API and they're shipped with  APK itself (/assets/bundle.zip). The tool's already built to search for those assets (more likely to, if you have full swf scripts decompiled), and if its not found on your end, you need to either pull assets directly from your device using the tool or manually extract them from APK and put it to `dump/` directory along with other asset dumps.

So if you want to extract those assets manually, follow the next steps.

1. Unpack application APK file.
2. Locate the bundled assets saved in `PATH_TO_UNPACKED_APK/assets/bundle.zip`.
3. Unzip it.
4. Copy all the contents inside `bundle.zip/production/bundle` `bundle.zip/production/medium_bundle`  into `WORK_DIRECTORY/dump/upload`. WORK_DIR is the Extraction Directory you selected from the tool.  (Make sure copied raw asset file paths are look like `WORK_DIR/dump/upload/73/4130924e07d945ae79acac1599758c4e50c432`)
5. Open `WORK_DIR/metadata.json` file and modify the key `lockedHashMap` value to false.
5.1 If you want to confirm everything was done correctly, try executing the command `image scene/general/sprite_sheet.png`. If that command successfully exports the designated asset then you're good to go.
6. Try extracting assets again.

If you can't still find assets after 6 but command in 5.1 works, make sure you turned on the `Search ActionScripts for assets` option and put all the decompiled SWF scripts in the right location. or you can try manually extract them one by one using commands. note that the paths you mentioned above are generated paths and they're actually included in one same sprite file named `scene/general/sprite_sheet` so you'd want to run `sprite scene/general/sprite_sheet` command to crop the image and save cropped sprite to designated path.

**Comment by michaelcurry** [comment]
This worked perfectly! I am going to take what you wrote above, and add it to the documentation I am writing (targeting a PR mid next week).  Thank you
