### ISSUE TITLE
Support for Bluestacks 5?

### ISSUE THREAD

**Issue by lullinglore** [ScripterSugar/wdfp-extractor#2]
```
Target region set as gl
Initializing extraction process.
scanning connected devices.
Error ocurred while extraction: Command failed: C:\Users\noral\AppData\Local\Programs\wdfp-extractor\resources\assets\adb\adb.exe connect 127.0.0.1:62025 * daemon not running; starting now at tcp:5037 could not read ok from ADB Server * failed to start daemon error: cannot connect to daemon
scanning connected devices.
1 device(s) found.
Connected to device emulator-5554
Error ocurred while extraction: Command failed: C:\Users\noral\AppData\Local\Programs\wdfp-extractor\resources\assets\adb\adb.exe -s emulator-5554 root adb: unable to connect for root: closed
```
Hi, I have tried to extract the assets from Bluestacks 5, but apparently it's not working (as seen in the log, the first time I started extraction I got an error, when retrying I got a different error; I keep getting this last error everytime I retry now)

I'm using Windows 10 and have installed Java. I would have installed Nox too if it wasn't for its virus... That's why I prefer using Bluestacks.

I'm not sure what other information you might need? I really need these assets for studying its art (especially animations and backgrounds), so I'm willing to help as much as I can!

**Comment by ScripterSugar** [comment]
It seems like your bluestacks not permitting the root access of ADB, which is required to access data directory of instance. I haven't dig around with bluestacks yet, but you'd like to check if there's any option in bluestacks preferences that permits the use of root adbd access, or at least make sure you've turned on the preferences that's related with the rooting and such.

**Comment by lullinglore** [comment]
There was this special advanced option:
![image](https://user-images.githubusercontent.com/47358820/155762870-b7ce0e8d-e39f-43a4-b072-88e25e1bcb34.png)

When I turned it on and tried again, it worked! Well, I just started extraction so I'll be updating after it finishes, and see whether everything went as expected. So far there doesn't seem to be any problems.

**UPDATE:**
There was a problem during extraction, here's the error message I got:
![image](https://user-images.githubusercontent.com/47358820/155770153-418e32fc-ca52-44c3-819c-0061541584bd.png)

And the log:
```
scanning connected devices.
1 device(s) found.
Connected to device 127.0.0.1:5555
ADB connected as root.
Adb shell connected.
Extracting Package APK...
APK version mismatch - exporting new APK...
APK extracted and saved to D:\Files\0. Inbox\flipper/apk.apk
SWF checksum mismatch - decompile swf and export essential scripts... (This might take more than several minutes.)
SWF Extraction successful.
Error ocurred while extraction: PROHIBITED_DATA_PERMISSION
```

**Comment by ScripterSugar** [comment]
as it says, you need your device to be rooted if you want to extract asset files from it. nothing I can help here if you can't get a rooted emulator or device.

**Comment by lullinglore** [comment]
Oooh I see! I did not know what "rooted" meant so I skipped it -- I rooted my Bluestacks now and am retrying, hopefully everything works now.
Thanks for your help!

UPDATE:
No luck, the same error pops up... My emulator is rooted without doubt (used Root Checker). Maybe the extractor simply doesn't work with Bluestacks yet. So I'll keep this issue open, I hope you'll be able to look into it!

**Comment by ScripterSugar** [comment]
I guess bluestack's using modified adbd which doesnt allow file listing access to the /data directory then. In this case I can make my tool to try full asset dumps on every attempts but it will hurt the extraction performance a lot. I'll look into the issue in this weekend if possible.

**Comment by ScripterSugar** [comment]
Should be resolved in latest update. Try updating to version ^0.3.12.
