### ISSUE TITLE
Failed to pull assets from api from jp server

### ISSUE THREAD

**Issue by wingzhingling** [ScripterSugar/wdfp-extractor#22]
Hi,i tried to pull assets from api from jp server,but the program throwed an error.
![Snipaste_2023-02-20_17-02-02](https://user-images.githubusercontent.com/9023663/220060294-a553cbf9-0a50-4cb7-8030-dc9f5358d87a.png)

The links of resource files were successfully fetched.But the files were not downloaded correctly,and caused the error in unzip progress.
I also tried to pull assets from en server and there's no error.I guess it may be blocked from downloading files from jp server.
![Snipaste_2023-02-20_17-07-08](https://user-images.githubusercontent.com/9023663/220061344-28e7676f-4fa1-4dec-8ca4-cded039308ed.png)
![Snipaste_2023-02-20_17-04-06](https://user-images.githubusercontent.com/9023663/220061839-d6ccdaec-f1f8-462c-903d-507708db61cd.png)

**Comment by wingzhingling** [comment]
UPDATE:I changed the download interval from 100ms to 1000ms,and it works now.
https://github.com/ScripterSugar/wdfp-extractor/blob/f6dde629cfabf7c3a5574b0480fa61349bc895f3/src/main/wf/index.ts#L2334

to
`await sleep(1000); `

**Comment by ScripterSugar** [comment]
api asset downloading isn't really stable atm. right now my best recommendation is to try again until it gets done. any PR to improve this will be appreciated.
