### ISSUE TITLE
Assets with dashes ("-") in paths not being extracted

### ISSUE THREAD

**Issue by bnnm** [ScripterSugar/wdfp-extractor#23]
Seen in a few BGM assets, maybe affects other types (only checked BGM). Assets are downloaded with hashed names in `dump/` but a few with dashes aren't extracted to `output/`.

For example, `bgm/world_brave/story/seven_story_10-1.mp3` (`3b/384970fbe0e798d766eeda9b0650eebc39d578`), `bgm/event/xm19-event/event_battle_christmas_boss.mp3` (`80/fb72cc9f98d010b26ced9d80ef723627d7f825`) and so on, referenced in master bgm_asset.orderedmap table.

My base output dir is a simple path with only letters and no numbers/dashes/etc if that matters, all other bgm extracted ok.

**Comment by ScripterSugar** [comment]
Thanks for the information. I'll look into this when I have some spare time

**Comment by ScripterSugar** [comment]
Closed by #24 

Resolved in version 0.6.4
