### ISSUE TITLE
r.replace is not a function

### ISSUE THREAD

**Issue by FinecoFinit** [ScripterSugar/wdfp-extractor#26]
error while extracting data
![image](https://github.com/ScripterSugar/wdfp-extractor/assets/22540805/bfb2e95d-d7f5-467f-a0b2-c1f8799b7ab5)

**Comment by PaJir** [comment]
Just remove the file named "asFilePaths.lock" in your Extraction Directory. The error is occurring due to the code snippet "{}.replace()".

**Comment by ScripterSugar** [comment]
Resolved as of version 0.6.9, added type checking for the path list
