### ISSUE TITLE
Directory with space is not supported

### ISSUE THREAD

**Issue by nnguyen259** [ScripterSugar/wdfp-extractor#9]
When picking a directory for the extraction, if the directory contains a space character (D:\World Flipper) there will be an error even though it's a valid directory. It works with underscore though

![image](https://user-images.githubusercontent.com/20191612/179403762-baedb1b8-ab89-4225-a2a8-a92e177a9459.png)

**Comment by ScripterSugar** [comment]
This is known issue as stated in documentation. Whitespaces were intentionally blocked since they're causing problems while extraction process, so we need to fix that part first.
